language: node_js
os: linux
node_js:
  - '10'
cache:
  npm: true
  directories:
    - "node_modules"
before_install:
  - npm install -g npm@latest
install:
  - npm ci
  - npm run lerna:bootstrap
  - npm run lerna:build
jobs:
  include:
    - stage: Test
      name: "Test"
      script:
        - npm run lint
        - npm run coverage
        - npm run snyk:test
before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
deploy:
  provider: script
  script: "npm run lerna:deploy"
  skip_cleanup: true
  on:
    tags: true
