language: node_js
os: linux
node_js:
- '10'
before_install:
- npm install -g npm@latest
install:
- npm install
- npm run build
jobs:
  include:
  - stage: Test
    name: Unit tests
    script:
    - npm run coverage
    - npm run snyk
deploy:
  provider: npm
  edge: true
  email: james.simpson@securetrading.com
  api_key:
    secure: Zhc7WbTcCtL4cNCiALElC2rDlFqnq+ChVRUh/EIdwbp0an6gZJv+tmHpgeyKjec/No4NIi5HuhwgRjMeMM4xXzhN9ZwxtiBudy4brAzD63sK+gO5K60wnvqr7e02lZ+F6cBV4l+rGDwxoDZapGQ4W9GyQoi0oyIP8NEevHROBOTobodOUyyH+f5SRmONWSv7DBdqLPn5JQc2OKGfqslRIddxSCExqEv0AI5G8HHNG/XyvgIOSWPMJuJ683YnDgu36GQMxx8pCjytSpLaV5Rhc8OFBiNbJIVzcB63XTqhS4HYli6+Qra7BRaTWtDNaJuftoOqSFvCMz2ghdJHQt7RSn89pVBJVc4BNSoEjfzfBk9KKD3Rj87vwV9u16IMd/Nv3u+HBpQfxMShzo4f+tBXfHraThGv5oIlz0YceEqio2x5SOpJoYXDN+wKCeubGKhIim86BuiX+cIdPpKF6xzHexlMEpZqKdBTEs3lirbJdC927XO2FICMixK+DNMRcI4hWiGprh4sM7JpFnhTCCjR0sN1yBHhGzwaEw9y0w9rQjL0pXFIzRnu/6RdpyaVHjfI6WG/58xFg0bP2BVoUSlKQjqIFlPNGA01zaNnQgr8Pinn856mG6nvgMvUwcPmmMvYsgF7iMVL/FvkgUQ8RR1ZYmsx+LB36Vo3TWjXUT7QZhQ=
  on:
    tags: true
