language: node_js
os: linux
node_js:
- '10'
before_install:
- npm install -g npm@latest
install:
- npm install
- npm run build
jobs:
  include:
  - stage: Test
    name: Unit tests
    script:
    - npm run coverage
    - npm run snyk
deploy:
  provider: npm
  email: james.simpson@securetrading.com
  api_key:
    secure: pfLdgGfwuXDOycV/AXetnZKd9ejEBRuhUwAMKATsslbwW6q+3fPjx4x87R3mrPbuqPG0VbHoFlaR5grViMFmzQbIRUXWqymcBhyXH1irJoykQFV/FmFnWlKRI2S/eF6mKwocaLI4pplNewRaDMB2FLh7F8dLLfw69AB8Z2mvICQoZWJQN5uOJXGzsT4uoQs7/JH17uOr+EbUuB0S/hhh0nEtLOK0RgZrscFf7AOot7v7zQ48m74/QxUxizJ27swRezEPZqa1pkhZEExrJeL0GrVbg98OE92THvJcL6+QVSv391eGa4QjQfoWKybT6zQisSiImMOF26opELNQWdVbJrnMhtbZKI01FniRancqUEVMW8U44goSUvHOFwFLBPLAkgjcqBpbz80ZGBj10lsg4GNpYLtPPdX7zLrbnnpzNbOdtmN1pwETAFknKG6HWQ6phuhNTYU/yA0Z5jc0oAh7Fi9Q9aRPhf25z4qL2DaLmCP3UjtP9qh5d96rkFMSFM6HuzW849KSN3T4lO3J6TaxYBQ4yUnmsWojdqC36S3DjCKUtLLzpYqYyIGahRg0KqWLHG+shYpfHJrbIajknB8cJtbeiVYA9As21uKiQeo+GPqVWA/8y5kKHIBlT6Iwy23tMlJRb7JoGSESS3uWT7A2RRfGAmKGKgWYy7NnRSn3VcI=
  on:
    tags: true
