language: node_js
os: linux
node_js:
  - '10'
cache:
  npm: true
  directories:
    - "node_modules"
before_install:
  - npm install -g npm@latest
install:
  - npm install
  - npm run lerna:bootstrap
  - npm run lerna:build
jobs:
  include:
    - stage: Test
      name: "Lint"
      script: npm run lint
    - name: "Unit test"
      script: npm run coverage
    - name: "Snyk"
      script: npm run snyk:test
deploy:
  provider: script
  script: "npm run lerna:deploy"
  skip_cleanup: true
  on:
    all_branches: true
  # on:
  #  tags: true
