language: node_js
os: linux
node_js:
  - '10'
before_install:
  - npm install -g npm@latest
install:
  - npm install
  - npm run lerna:bootstrap
  - npm run lerna:build
jobs:
  include:
    - stage: Test
      name: Unit tests
      script:
        - npm run coverage
        - npm run lint
        - npm run snyk:test
deploy:
  provider: script
  script: "npm run lerna:deploy"
  on:
    all_branches: true
  # on:
  #  tags: true
