language: node_js
node_js:
  - '10'
before_install:
  - npm install -g npm@latest
install:
  - npm install
  - npm run build
jobs:
  include:
    - stage: 'Test'
      name: 'Unit tests'
      script:
        - npm run coverage
        - npm run snyk
